const choices = [
    "the women's bathroom at a nightclub",
    "a museum of antiquities",
    "a brothel",
    "a speed dating club",
    "an empty field",
    "a cornfield",
    "a funeral home",
    "the belly of a whale",
    "an executioner's cart",
    "a murder mystery party",
    "the gallows",
    "a sinking ship",
    "an internet cafe",
    "a bath house",
    "the drunk tank at the local jail",
    "the gates of the afterlife",
    "a school playground",
    "a plague pit",
    "a cruise ship",
    "a border crossing",
    "a wedding",
    "free fall",
    "a caravan",
    "a high speed train",
    "a retirement home",
    "a graveyard",
    "the grave!",
    "a futurism festival",
    "an underground market",
    "a sports riot",
    "a chariot race",
    "a colosseum",
    "a wrestling match",
    "a witch's hut",
    "a cave under the sea",
    "a tavern, i guess",
];
const choice = choices[Math.floor(Math.random() * choices.length)];
document.querySelector("#textGoHere").textContent = "Your next campaign begins in " + choice + ".";