const choices = [
    "in the women's bathroom at a nightclub.",
    "in a museum of antiquities.",
    "in a brothel.",
    "in a speed dating club.",
    "in an empty field.",
    "in a cornfield.",
    "in a funeral home.",
    "in the belly of a whale.",
    "in an executioner's cart.",
    "in a murder mystery party.",
    "in the gallows.",
    "in a sinking ship.",
    "in an internet cafe.",
    "in a bath house.",
    "in the drunk tank at the local jail.",
    "in the gates of the afterlife.",
    "in a school playground.",
    "in a plague pit.",
    "on a cruise ship.",
    "at a border crossing.",
    "at a wedding.",
    "in free fall.",
    "in a caravan.",
    "on a high speed train.",
    "in a retirement home.",
    "in a graveyard.",
    "in the grave!",
    "at a futurism festival.",
    "in an underground market.",
    "at a sports riot.",
    "in a chariot race.",
    "in a colosseum.",
    "in a wrestling match.",
    "in a witch's hut.",
    "in a cave under the sea.",
    "in a tavern, i guess.",
    "around the dinner table, piled high with books and dice.",
    "aboard a space station.",
    "in a stall at a bazaar.",
    "at an underground poker game.",
    "in rural Maine.",
    "in a hostage situation.",
    "in a community storm shelter.",
    "in a haunted forest.",
    "in a bustling city market.",
    "in a sunken temple.",
    "in an underground cave system.",
    "in a frozen wasteland.",
    "in an abandoned castle.",
    "in a mysterious desert oasis.",
    "in a dark and treacherous swamp.",
    "in a cursed tomb.",
    "in a massive underground city.",
    "in a thriving jungle village.",
    "in a besieged fortress.",
    "in another world realm.",
    "in a hidden underground laboratory.",
    "in a giant treehouse.",
    "in a pirate's cove.",
    "on a massive floating city.",
    "in an eerie graveyard.",
    "in a massive, ancient library.",
    "in a sunken shipwreck.",
    "in a secret underground bunker.",
    "on a hot air balloon.",
    "in a circus tent.",
    "in a futuristic city.",
    "on a deserted island.",
    "in a forbidden temple.",
    "in a time travel experiment gone wrong.",
    "in a haunted mansion.",
    "in a post-apocalyptic wasteland.",
    "in a casino heist.",
    "in a virtual reality game.",
    "in a gladiator arena.",
    "in a hidden forest shrine.",
    "on a flying carpet.",
    "in a top-secret government facility.",
    "on a frozen tundra.",
    "in a dystopian society.",
    "in a massive concert venue.",
    "at a remote mountain lodge.",
    "on a steam-powered airship."
];

function getChoice() {
    choice = choices[Math.floor(Math.random() * choices.length)];
    document.querySelector("#textGoHere").textContent = "Your next campaign begins " + choice;
}

getChoice();
